# Frontend Development Dockerfile
FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm ci

# Копируем исходный код
COPY . .

EXPOSE 5173

# Запуск dev сервера
CMD ["npm", "run", "dev", "--", "--host"]
